version: "2"
services:
    wordpress:
        build: ./docker/wordpress
        ports:
            - "8089:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_NAME: "wordpress"
            WORDPRESS_DB_USER: "wordpress"
            WORDPRESS_DB_PASSWORD: "wordpress"
        volumes:
            - ./:/var/www/html/wp-content/themes/aetherium
    db:
        image: mysql:latest
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: "wordpress"
            MYSQL_USER: "wordpress"
            MYSQL_PASSWORD: "wordpress"

volumes:
    db-data:
        driver: local
